--- 
framework: 
  AdminMode: 0
  SetupMode: 1
  ApplicationClass: RT
  ApplicationName: RT
  ApplicationUUID: EAFC6FF2-5E8D-11DC-9FAD-91A9684ED971
  ConfigFileVersion: 4
  Database: 
    CheckSchema: 0
    Database: rt4
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: root
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - LetMe: {}
    - SkeletonApp: {}
    - REST: {}
    - ErrorTemplates: {}
    - CompressedCSSandJS: {}
    - User: {}
    - Authentication::Password:
        login_by: username
    - I18N:
        js: 0
    - IEFixes:
        js:
          - IE7
          - IE8
          - ie7-recalc
          - ie7-squish
    - TestServerWarnings:
        clear_screen: 0
    - Config:
        config_url: '/Admin/Global/Elements/ConfigJifty'
        restart_url: '/Admin/Global/Jifty/restart.html'
        after_restart_url: '/Admin/Global/System.html'
        wait_seconds: 10
    - SetupWizard:
        add_steps:
          - template: basics
            header: RT Basics
    - WyzzEditor: {}
  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: RT::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/html
